FROM pantsel/konga:latest
WORKDIR /app

# 1. Instalamos el driver nuevo
RUN npm install --save sails-postgresql@1.0.2

# 2. FUERZA BRUTA: Reemplazamos la línea sin importar comillas o espacios.
# Le decimos: "Cualquier línea que tenga 'require' y 'sails-postgresql' y 'pg', cámbiala".
RUN sed -i 's|require(.*sails-postgresql.*pg.*)|require("pg")|g' /app/makedb/dbs/pg.js

EXPOSE 1337